//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunglePath.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JunglePath.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap block {
            get {
                object obj = ResourceManager.GetObject("block", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gameBack {
            get {
                object obj = ResourceManager.GetObject("gameBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap How_To_Play {
            get {
                object obj = ResourceManager.GetObject("How_To_Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] jungleSounds {
            get {
                object obj = ResourceManager.GetObject("jungleSounds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;block x=&quot;140&quot; y =&quot;100&quot; type =&quot;null&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;100&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;100&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;100&quot; type=&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;540&quot; y=&quot;100&quot; type=&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;640&quot; y=&quot;100&quot; type=&quot;win&quot;/&gt;
        ///  &lt;block x=&quot;740&quot; y=&quot;100&quot; type=&quot;path&quot;/&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;180&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;180&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;180&quot; type= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level10 {
            get {
                return ResourceManager.GetString("Level10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;block x=&quot;140&quot; y =&quot;100&quot; type =&quot;null&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;100&quot; type =&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;100&quot; type =&quot;null&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;540&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;640&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;740&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;180&quot; type =&quot;null&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;180&quot; type=&quot;null&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;block x=&quot;140&quot; y =&quot;100&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;100&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;100&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;540&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;640&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;740&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;180&quot; type =&quot;start&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;180&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;180&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;180&quot; type=&quot;mon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;100&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;100&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;100&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;100&quot; type=&quot;path&quot;/&gt;
        ///  &lt;block x=&quot;540&quot; y=&quot;100&quot; type=&quot;path&quot;/&gt;
        ///  &lt;block x=&quot;640&quot; y=&quot;100&quot; type=&quot;path&quot;/&gt;
        ///  &lt;block x=&quot;740&quot; y=&quot;100&quot; type=&quot;path&quot;/&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;180&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;180&quot; type=&quot;monst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;100&quot; type =&quot;start&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;100&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;100&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;540&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;640&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;740&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;180&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;180&quot; type=&quot;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level5 {
            get {
                return ResourceManager.GetString("Level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;100&quot; type =&quot;start&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;100&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;100&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;100&quot; type=&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;540&quot; y=&quot;100&quot; type=&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;640&quot; y=&quot;100&quot; type=&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;740&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;180&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;180&quot; t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level6 {
            get {
                return ResourceManager.GetString("Level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;100&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;100&quot; type =&quot;start&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;100&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;540&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;640&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;740&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;180&quot; type =&quot;path&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;180&quot; type [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level7 {
            get {
                return ResourceManager.GetString("Level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;100&quot; type =&quot;null&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;100&quot; type =&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;100&quot; type =&quot;null&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;540&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;640&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;740&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;180&quot; type=&quot;mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level8 {
            get {
                return ResourceManager.GetString("Level8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;100&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;100&quot; type =&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;100&quot; type =&quot;null&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;100&quot; type=&quot;null&quot;/&gt;
        ///  &lt;block x=&quot;540&quot; y=&quot;100&quot; type=&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;640&quot; y=&quot;100&quot; type=&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;740&quot; y=&quot;100&quot; type=&quot;win&quot;/&gt;
        ///
        ///  &lt;block x=&quot;140&quot; y =&quot;180&quot; type =&quot;start&quot;/&gt;
        ///  &lt;block x =&quot;240&quot; y =&quot;180&quot; type =&quot;monster&quot;/&gt;
        ///  &lt;block x=&quot;340&quot; y =&quot;180&quot; type =&quot;null&quot;/&gt;
        ///  &lt;block x =&quot;440&quot; y=&quot;180&quot; type= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level9 {
            get {
                return ResourceManager.GetString("Level9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menuBack {
            get {
                object obj = ResourceManager.GetObject("menuBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p2Down {
            get {
                object obj = ResourceManager.GetObject("p2Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p2Left {
            get {
                object obj = ResourceManager.GetObject("p2Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p2Right {
            get {
                object obj = ResourceManager.GetObject("p2Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p2Up {
            get {
                object obj = ResourceManager.GetObject("p2Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap path {
            get {
                object obj = ResourceManager.GetObject("path", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pDown {
            get {
                object obj = ResourceManager.GetObject("pDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pLeft {
            get {
                object obj = ResourceManager.GetObject("pLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pRight {
            get {
                object obj = ResourceManager.GetObject("pRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pUp {
            get {
                object obj = ResourceManager.GetObject("pUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Highscores&gt;
        ///  &lt;name&gt;ABA&lt;/name&gt;
        ///  &lt;score&gt;00000&lt;/score&gt;
        ///  &lt;name&gt;AAA&lt;/name&gt;
        ///  &lt;score&gt;00000&lt;/score&gt;
        ///  &lt;name&gt;AAA&lt;/name&gt;
        ///  &lt;score&gt;00000&lt;/score&gt;
        ///  &lt;name&gt;AAA&lt;/name&gt;
        ///  &lt;score&gt;00000&lt;/score&gt;
        ///  &lt;name&gt;AAA&lt;/name&gt;
        ///  &lt;score&gt;00000&lt;/score&gt;
        ///  &lt;name&gt;AAA&lt;/name&gt;
        ///  &lt;score&gt;00000&lt;/score&gt;
        ///  &lt;name&gt;AAA&lt;/name&gt;
        ///  &lt;score&gt;00000&lt;/score&gt;
        ///  &lt;name&gt;AAA&lt;/name&gt;
        ///  &lt;score&gt;00000&lt;/score&gt;
        ///  &lt;name&gt;AAA&lt;/name&gt;
        ///  &lt;score&gt;00000&lt;/score&gt;
        ///  &lt;name&gt;AAA&lt;/name&gt;
        ///  &lt;score&gt;00000&lt;/score&gt;
        ///&lt;/Highscores&gt;
        ///.
        /// </summary>
        internal static string scores {
            get {
                return ResourceManager.GetString("scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selectBlock {
            get {
                object obj = ResourceManager.GetObject("selectBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selectButton {
            get {
                object obj = ResourceManager.GetObject("selectButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slime {
            get {
                object obj = ResourceManager.GetObject("slime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap treasure {
            get {
                object obj = ResourceManager.GetObject("treasure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
